### ISSUE TITLE
Entitlements API - need to add support for show_tokens to the sync cmd

### ISSUE THREAD

**Issue by alancarson** [cloudsmith-io/cloudsmith-api#1]
It currently breaks the CLI (which has support for `show_tokens`) on the `sync` command

` cloudsmith ents sync acarson/repo_abc repo_def -F json -y
Syncing entitlements from the integration repository to the test repositoryTraceback (most recent call last):
  File "/usr/local/bin/cloudsmith", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/cli/commands/entitlements.py", line 35, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/cli/decorators.py", line 66, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/cli/decorators.py", line 92, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/cli/decorators.py", line 128, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/cli/decorators.py", line 183, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/cli/commands/entitlements.py", line 470, in sync
    owner=owner, repo=repo, source=source, show_tokens=show_tokens
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_cli/core/api/entitlements.py", line 124, in sync_entitlements
    show_tokens=show_tokens
  File "/usr/local/lib/python2.7/dist-packages/cloudsmith_api/apis/entitlements_api.py", line 1150, in entitlements_sync_with_http_info
    " to method entitlements_sync" % key
TypeError: Got an unexpected keyword argument 'show_tokens' to method entitlements_sync`

**Comment by lskillen** [comment]
Fixed in the 0.35 API release. :)
